#!/bin/bash
# start script for yafsm fsm generation
# required perl, perl-xml-simple, xmllint
YAFSM_PATH=`dirname $(readlink -f $0)`

if [ -z $1 ] ; then
  echo "missing definition of State Machine XML file"
  exit 1
fi
if [ -e $1 ] ; then
  echo "validating fsm $1"
  xmllint --noout --schema $YAFSM_PATH/yafsm.xsd $1

  #echo $?
  if [ 0 -eq $? ] ; then
    echo "generating fsm $1"
    perl -I$YAFSM_PATH -f $YAFSM_PATH/YaFsm.pl --fsm=$1 --gencode --genview
  fi
  fsmdir=`echo $1 | tr "[:upper:]" "[:lower:]"`
  fsmdir=${fsmdir%.xml}
  #echo $fsmdir

  if [ -n "$fsmdir" ] ; then
    if [ -d $fsmdir ] ; then
      echo update files from $YAFSM_PATH/codeimpl/cpp/ to $fsmdir/code
      cp -pu $YAFSM_PATH/codeimpl/cpp/inc/*.* $fsmdir/code
      cp -pu $YAFSM_PATH/codeimpl/cpp/qt4/*.* $fsmdir/code
    fi
  fi
else
  echo "file $1 not existing"
  exit 1
fi
#yafsm --fsm=
#--gendot
#--dottype
#--outdot
#--gendsc
#--gencode
#--outcode
